/**
 * Terms of Service Page
 *
 * Displays the company's terms of service, including acceptable use,
 * intellectual property, disclaimers, and liability. Tailored for healthcare
 * SaaS company.
 */

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - Nexus',
  description: 'Read the terms and conditions governing the use of Nexus services, including user responsibilities, intellectual property rights, and limitations of liability.',
};

export default function TermsOfServicePage() {
  const lastUpdated = '2025-10-16';
  const effectiveDate = '2025-10-16';

  return (
    <article className="legal-page">
      <div className="legal-page-hero">
        <div className="container">
          <div className="legal-page-header">
            <h1 className="legal-page-title">Terms of Service</h1>
            <div className="legal-page-meta">
              <p>
                <strong>Last Updated:</strong> {lastUpdated}
              </p>
              <p>
                <strong>Effective Date:</strong> {effectiveDate}
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="legal-page-content-wrapper">
        <div className="container">
          <div className="legal-page-content">
            <section className="legal-section">
              <p className="legal-intro">
                These Terms of Service ("Terms") govern your access to and use of the Nexus platform
                and services ("Services"). By accessing or using our Services, you agree to be bound
                by these Terms. If you do not agree to these Terms, do not use our Services.
              </p>
              <p className="legal-intro">
                <strong>IMPORTANT:</strong> These Terms include provisions that limit our liability to
                you and require you to resolve disputes with us through arbitration on an individual
                basis, not as part of any class or representative action. Please read these Terms carefully.
              </p>
            </section>

            <section className="legal-section">
              <h2>1. Definitions</h2>

              <ul>
                <li><strong>"You," "Your," "User," "Customer"</strong> refers to the individual or entity accessing or using the Services.</li>
                <li><strong>"We," "Us," "Our," "Nexus"</strong> refers to the company providing the Services.</li>
                <li><strong>"Services"</strong> refers to the Nexus AI-powered radiology governance platform, including all features, tools, software, and related services.</li>
                <li><strong>"Content"</strong> refers to all data, information, images, reports, and materials processed through or generated by the Services.</li>
                <li><strong>"PHI"</strong> refers to Protected Health Information as defined under HIPAA.</li>
                <li><strong>"BAA"</strong> refers to a Business Associate Agreement executed between you and Nexus.</li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>2. Acceptance of Terms</h2>

              <h3>2.1 Agreement</h3>
              <p>
                By creating an account, accessing the Services, or clicking "I Agree," you acknowledge
                that you have read, understood, and agree to be bound by these Terms and our Privacy Policy.
              </p>

              <h3>2.2 Authority</h3>
              <p>
                If you are using the Services on behalf of an organization, you represent and warrant
                that you have the authority to bind that organization to these Terms. In such cases,
                "you" and "your" refer to that organization.
              </p>

              <h3>2.3 Eligibility</h3>
              <p>
                You must be at least 18 years old and legally capable of entering into binding contracts
                to use the Services. Our Services are intended for healthcare organizations and professionals
                only.
              </p>
            </section>

            <section className="legal-section">
              <h2>3. Account Registration and Security</h2>

              <h3>3.1 Account Creation</h3>
              <p>
                To access certain features of the Services, you must create an account. You agree to:
              </p>
              <ul>
                <li>Provide accurate, current, and complete information</li>
                <li>Maintain and promptly update your account information</li>
                <li>Keep your password secure and confidential</li>
                <li>Notify us immediately of any unauthorized access or security breach</li>
                <li>Accept responsibility for all activities under your account</li>
              </ul>

              <h3>3.2 Account Credentials</h3>
              <p>
                You are responsible for safeguarding your account credentials. We are not liable for any
                loss or damage arising from your failure to protect your account information.
              </p>

              <h3>3.3 Account Suspension</h3>
              <p>
                We reserve the right to suspend or terminate your account if we suspect unauthorized
                access, violation of these Terms, or any activity that threatens the security or
                integrity of the Services.
              </p>
            </section>

            <section className="legal-section">
              <h2>4. Use of Services</h2>

              <h3>4.1 License Grant</h3>
              <p>
                Subject to your compliance with these Terms, we grant you a limited, non-exclusive,
                non-transferable, revocable license to access and use the Services for your internal
                business purposes in the healthcare field.
              </p>

              <h3>4.2 Restrictions</h3>
              <p>You agree NOT to:</p>
              <ul>
                <li>Reverse engineer, decompile, or disassemble any part of the Services</li>
                <li>Access or use the Services to build a competitive product or service</li>
                <li>Copy, modify, distribute, sell, or lease any part of the Services</li>
                <li>Remove or alter any proprietary notices or labels</li>
                <li>Use automated systems (bots, scrapers) to access the Services without authorization</li>
                <li>Interfere with or disrupt the Services or servers/networks connected to the Services</li>
                <li>Attempt to gain unauthorized access to any systems or networks</li>
                <li>Use the Services for any illegal or unauthorized purpose</li>
                <li>Transmit any viruses, malware, or other harmful code</li>
              </ul>

              <h3>4.3 Acceptable Use</h3>
              <p>
                You agree to use the Services only for lawful purposes and in accordance with:
              </p>
              <ul>
                <li>All applicable laws and regulations, including HIPAA, FDA regulations, and state healthcare laws</li>
                <li>Professional standards and ethics for healthcare providers</li>
                <li>Your organization's internal policies and procedures</li>
                <li>Any additional terms specified in your service agreement or BAA</li>
              </ul>

              <h3>4.4 Healthcare Disclaimer</h3>
              <p>
                <strong>IMPORTANT:</strong> The Services are designed to assist healthcare professionals
                but do NOT replace professional medical judgment. Users remain solely responsible for:
              </p>
              <ul>
                <li>All clinical decisions and patient care</li>
                <li>Verification of AI-generated outputs and recommendations</li>
                <li>Compliance with standard of care and clinical protocols</li>
                <li>Final diagnosis and treatment decisions</li>
              </ul>
              <p>
                The Services are clinical decision support tools only and should not be the sole basis
                for diagnostic or treatment decisions.
              </p>
            </section>

            <section className="legal-section">
              <h2>5. HIPAA Compliance and PHI</h2>

              <h3>5.1 Business Associate Agreement</h3>
              <p>
                If you are a HIPAA-covered entity or business associate and will use the Services to
                process PHI, you must execute a Business Associate Agreement (BAA) with us. Contact us
                at <a href="mailto:info@hiveomics.com">info@hiveomics.com</a> to obtain a BAA.
              </p>

              <h3>5.2 PHI Handling</h3>
              <p>
                When processing PHI under a BAA, we will:
              </p>
              <ul>
                <li>Use and disclose PHI only as permitted by the BAA and HIPAA</li>
                <li>Implement appropriate safeguards to protect PHI</li>
                <li>Report security incidents and breaches as required by law</li>
                <li>Make PHI available for access, amendment, or accounting as required</li>
                <li>Return or destroy PHI upon termination as directed</li>
              </ul>

              <h3>5.3 Your Responsibilities</h3>
              <p>
                You are responsible for:
              </p>
              <ul>
                <li>Obtaining all necessary patient authorizations and consents</li>
                <li>Ensuring your use of the Services complies with HIPAA and other privacy laws</li>
                <li>Properly de-identifying data when appropriate</li>
                <li>Implementing minimum necessary access controls</li>
                <li>Training your workforce on HIPAA requirements</li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>6. Intellectual Property Rights</h2>

              <h3>6.1 Our Intellectual Property</h3>
              <p>
                The Services, including all software, algorithms, AI models, documentation, designs,
                trademarks, and other materials (excluding Your Content) are owned by Nexus and are
                protected by copyright, patent, trademark, and other intellectual property laws.
              </p>

              <h3>6.2 Your Content</h3>
              <p>
                You retain all ownership rights to the data and content you upload or input into the
                Services ("Your Content"). By using the Services, you grant us a limited license to:
              </p>
              <ul>
                <li>Process Your Content to provide the Services</li>
                <li>Use de-identified and aggregated data to improve our AI models and Services</li>
                <li>Create anonymized research and statistical analyses</li>
              </ul>
              <p>
                This license terminates when you delete Your Content or terminate your account, except
                for de-identified data that cannot be re-associated with you.
              </p>

              <h3>6.3 Feedback</h3>
              <p>
                If you provide feedback, suggestions, or ideas about the Services, we may use them
                without any obligation to you. You grant us a perpetual, worldwide, royalty-free license
                to use, modify, and incorporate such feedback into our Services.
              </p>

              <h3>6.4 Trademark License</h3>
              <p>
                We grant you a limited license to use our trademarks solely to identify our Services
                in accordance with our brand guidelines. All goodwill generated from such use inures to
                our benefit.
              </p>
            </section>

            <section className="legal-section">
              <h2>7. Fees and Payment</h2>

              <h3>7.1 Subscription Fees</h3>
              <p>
                Access to the Services requires payment of subscription fees as specified in your
                service agreement or order form. Fees are due in advance and are non-refundable except
                as expressly stated in your agreement.
              </p>

              <h3>7.2 Payment Terms</h3>
              <ul>
                <li><strong>Billing:</strong> You authorize us to charge your payment method on file for all applicable fees</li>
                <li><strong>Renewal:</strong> Subscriptions automatically renew unless you cancel before the renewal date</li>
                <li><strong>Late Payment:</strong> Late payments may incur interest charges and service suspension</li>
                <li><strong>Taxes:</strong> Fees exclude applicable taxes, which you are responsible for paying</li>
              </ul>

              <h3>7.3 Fee Changes</h3>
              <p>
                We may change our fees with 30 days' notice. Continued use of the Services after fee
                changes constitutes acceptance of the new fees.
              </p>
            </section>

            <section className="legal-section">
              <h2>8. Service Availability and Modifications</h2>

              <h3>8.1 Service Availability</h3>
              <p>
                We strive to maintain high availability but do not guarantee uninterrupted or error-free
                operation. The Services may be unavailable due to:
              </p>
              <ul>
                <li>Scheduled maintenance (with advance notice when possible)</li>
                <li>Emergency maintenance or security patches</li>
                <li>Third-party service disruptions</li>
                <li>Force majeure events</li>
              </ul>

              <h3>8.2 Service Modifications</h3>
              <p>
                We reserve the right to modify, suspend, or discontinue any part of the Services at any
                time with reasonable notice. We will not be liable for any modification, suspension, or
                discontinuation.
              </p>

              <h3>8.3 Updates and Upgrades</h3>
              <p>
                We may update the Services with new features, bug fixes, or security patches. Updates
                may be applied automatically. Major changes will be communicated in advance when feasible.
              </p>
            </section>

            <section className="legal-section">
              <h2>9. Data Security and Breach Notification</h2>

              <h3>9.1 Security Measures</h3>
              <p>
                We implement industry-standard security measures to protect your data, including:
              </p>
              <ul>
                <li>Encryption in transit and at rest</li>
                <li>Access controls and authentication</li>
                <li>Regular security audits and testing</li>
                <li>Incident response procedures</li>
              </ul>

              <h3>9.2 Security Incidents</h3>
              <p>
                In the event of a security incident affecting your data:
              </p>
              <ul>
                <li>We will investigate and contain the incident promptly</li>
                <li>We will notify you in accordance with applicable law (HIPAA breach notification requirements for PHI)</li>
                <li>We will cooperate with you to mitigate harm</li>
                <li>We will document the incident for regulatory reporting</li>
              </ul>

              <h3>9.3 Your Security Obligations</h3>
              <p>
                You are responsible for:
              </p>
              <ul>
                <li>Maintaining secure systems and networks that access the Services</li>
                <li>Implementing appropriate workforce training</li>
                <li>Reporting suspected security incidents to us immediately</li>
                <li>Following security best practices</li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>10. Warranties and Disclaimers</h2>

              <h3>10.1 Limited Warranty</h3>
              <p>
                We warrant that the Services will perform substantially in accordance with our
                documentation under normal use. This warranty does not cover:
              </p>
              <ul>
                <li>Issues caused by misuse, modifications, or unauthorized access</li>
                <li>Third-party products or services</li>
                <li>Problems arising from Your Content or data quality</li>
                <li>Force majeure events</li>
              </ul>

              <h3>10.2 DISCLAIMER OF WARRANTIES</h3>
              <p className="legal-highlight">
                EXCEPT AS EXPRESSLY PROVIDED IN SECTION 10.1, THE SERVICES ARE PROVIDED "AS IS" AND
                "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT
                NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
                TITLE, OR NON-INFRINGEMENT.
              </p>
              <p className="legal-highlight">
                WE DO NOT WARRANT THAT:
              </p>
              <ul>
                <li>The Services will be uninterrupted, timely, secure, or error-free</li>
                <li>Results or outputs will be accurate, complete, or reliable</li>
                <li>All errors will be corrected</li>
                <li>The Services will meet your specific requirements</li>
              </ul>

              <h3>10.3 Medical Disclaimer</h3>
              <p className="legal-highlight">
                THE SERVICES ARE CLINICAL DECISION SUPPORT TOOLS ONLY. WE MAKE NO REPRESENTATIONS OR
                WARRANTIES REGARDING THE MEDICAL ACCURACY, RELIABILITY, OR COMPLETENESS OF AI-GENERATED
                OUTPUTS. HEALTHCARE PROFESSIONALS MUST EXERCISE INDEPENDENT MEDICAL JUDGMENT AND VERIFY
                ALL OUTPUTS BEFORE MAKING CLINICAL DECISIONS.
              </p>

              <h3>10.4 Regulatory Status</h3>
              <p>
                The Services may be subject to FDA regulation as a medical device. Regulatory status
                and clearances are specified in product documentation. You are responsible for verifying
                regulatory compliance for your intended use.
              </p>
            </section>

            <section className="legal-section">
              <h2>11. Limitation of Liability</h2>

              <h3>11.1 Limitation of Damages</h3>
              <p className="legal-highlight">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL NEXUS, ITS AFFILIATES,
                OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR:
              </p>
              <ul>
                <li>INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES</li>
                <li>LOSS OF PROFITS, REVENUE, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES</li>
                <li>PERSONAL INJURY OR PROPERTY DAMAGE</li>
                <li>MEDICAL MALPRACTICE OR HARM TO PATIENTS</li>
                <li>DAMAGES RESULTING FROM UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR DATA</li>
                <li>DAMAGES RESULTING FROM YOUR RELIANCE ON OR USE OF THE SERVICES</li>
              </ul>
              <p className="legal-highlight">
                EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
              </p>

              <h3>11.2 Liability Cap</h3>
              <p className="legal-highlight">
                OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR
                THE SERVICES SHALL NOT EXCEED THE GREATER OF:
              </p>
              <ul>
                <li>THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM, OR</li>
                <li>$500 USD</li>
              </ul>

              <h3>11.3 Exclusions</h3>
              <p>
                The limitations in this section do not apply to:
              </p>
              <ul>
                <li>Our obligations under a BAA for breaches of PHI</li>
                <li>Your breach of intellectual property rights</li>
                <li>Your violation of applicable laws</li>
                <li>Your indemnification obligations</li>
                <li>Liability that cannot be excluded or limited by law</li>
              </ul>

              <h3>11.4 Basis of the Bargain</h3>
              <p>
                You acknowledge that these limitations reflect a reasonable allocation of risk and are
                fundamental elements of the basis of the bargain between us. We would not be able to
                provide the Services on an economically reasonable basis without these limitations.
              </p>
            </section>

            <section className="legal-section">
              <h2>12. Indemnification</h2>

              <h3>12.1 Your Indemnification</h3>
              <p>
                You agree to indemnify, defend, and hold harmless Nexus and its affiliates, officers,
                directors, employees, agents, and licensors from any claims, damages, losses, liabilities,
                and expenses (including attorneys' fees) arising from:
              </p>
              <ul>
                <li>Your use or misuse of the Services</li>
                <li>Your breach of these Terms</li>
                <li>Your violation of any law or third-party rights</li>
                <li>Your Content or any data you provide</li>
                <li>Clinical decisions made using the Services</li>
                <li>Medical malpractice or patient harm claims</li>
              </ul>

              <h3>12.2 Process</h3>
              <p>
                We will notify you of any claim subject to indemnification and cooperate reasonably in
                the defense. We reserve the right to assume exclusive control of the defense at our
                expense.
              </p>
            </section>

            <section className="legal-section">
              <h2>13. Term and Termination</h2>

              <h3>13.1 Term</h3>
              <p>
                These Terms commence when you first access the Services and continue until terminated
                by either party.
              </p>

              <h3>13.2 Termination by You</h3>
              <p>
                You may terminate your account at any time by:
              </p>
              <ul>
                <li>Contacting customer support</li>
                <li>Following account closure procedures in your account settings</li>
                <li>Providing written notice per your service agreement</li>
              </ul>
              <p>
                Termination does not relieve you of payment obligations for services already rendered.
              </p>

              <h3>13.3 Termination by Us</h3>
              <p>
                We may terminate or suspend your access immediately without notice if:
              </p>
              <ul>
                <li>You breach these Terms</li>
                <li>Payment is past due</li>
                <li>Your use poses a security risk or legal liability</li>
                <li>Required by law</li>
                <li>You engage in fraudulent or illegal activity</li>
              </ul>

              <h3>13.4 Effect of Termination</h3>
              <p>
                Upon termination:
              </p>
              <ul>
                <li>Your right to access the Services immediately ceases</li>
                <li>We will make Your Content available for download for 30 days (unless legally prohibited)</li>
                <li>After 30 days, we may delete Your Content per our data retention policy</li>
                <li>Provisions that should survive termination will remain in effect (e.g., warranties, indemnification, limitations of liability)</li>
              </ul>

              <h3>13.5 PHI Upon Termination</h3>
              <p>
                For PHI, we will follow the data return or destruction procedures specified in the BAA,
                typically:
              </p>
              <ul>
                <li>Return all PHI in a usable format, or</li>
                <li>Destroy PHI if return is not feasible (with certification)</li>
                <li>Retain PHI only if required by law (with continued protection)</li>
              </ul>
            </section>

            <section className="legal-section">
              <h2>14. Dispute Resolution</h2>

              <h3>14.1 Informal Resolution</h3>
              <p>
                Before filing a claim, you agree to contact us at{' '}
                <a href="mailto:legal@hiveomics.com">legal@hiveomics.com</a> to attempt to
                resolve the dispute informally. We will attempt to resolve disputes within 60 days.
              </p>

              <h3>14.2 Binding Arbitration</h3>
              <p>
                If informal resolution fails, disputes will be resolved through binding arbitration
                rather than in court, except:
              </p>
              <ul>
                <li>Small claims court matters within jurisdictional limits</li>
                <li>Intellectual property disputes</li>
                <li>Claims for injunctive or equitable relief</li>
              </ul>

              <h3>14.3 Arbitration Rules</h3>
              <p>
                Arbitration will be conducted by the American Arbitration Association (AAA) under its
                Commercial Arbitration Rules. The arbitrator's decision is final and binding.
              </p>

              <h3>14.4 Class Action Waiver</h3>
              <p className="legal-highlight">
                YOU AND NEXUS AGREE THAT DISPUTES WILL BE RESOLVED ON AN INDIVIDUAL BASIS ONLY. YOU
                WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION, CLASS ARBITRATION, OR REPRESENTATIVE
                ACTION. THIS WAIVER IS ENFORCEABLE EVEN IF THE DISPUTE RESOLUTION MECHANISM FAILS.
              </p>

              <h3>14.5 Governing Law and Venue</h3>
              <p>
                These Terms are governed by the laws of [State], United States, without regard to
                conflict of law principles. Exclusive venue for any court proceedings (where permitted)
                is in [County], [State].
              </p>
            </section>

            <section className="legal-section">
              <h2>15. General Provisions</h2>

              <h3>15.1 Entire Agreement</h3>
              <p>
                These Terms, together with your service agreement, BAA (if applicable), and Privacy
                Policy, constitute the entire agreement between you and us regarding the Services and
                supersede all prior agreements.
              </p>

              <h3>15.2 Amendments</h3>
              <p>
                We may modify these Terms by posting updated terms on our website. Material changes
                will be notified via email or prominent notice. Continued use after changes constitutes
                acceptance. If you do not agree, discontinue use of the Services.
              </p>

              <h3>15.3 Severability</h3>
              <p>
                If any provision of these Terms is found invalid or unenforceable, the remaining
                provisions will remain in full force and effect. The invalid provision will be modified
                to achieve the original intent to the extent possible.
              </p>

              <h3>15.4 Waiver</h3>
              <p>
                Our failure to enforce any right or provision does not constitute a waiver. Any waiver
                must be in writing and signed by an authorized representative.
              </p>

              <h3>15.5 Assignment</h3>
              <p>
                You may not assign or transfer these Terms without our prior written consent. We may
                assign these Terms without restriction. Any attempted assignment in violation is void.
              </p>

              <h3>15.6 Force Majeure</h3>
              <p>
                Neither party is liable for failure to perform due to causes beyond reasonable control,
                including natural disasters, war, terrorism, labor disputes, government actions, or
                internet disruptions.
              </p>

              <h3>15.7 Export Compliance</h3>
              <p>
                The Services are subject to U.S. export control laws. You agree to comply with all
                applicable export laws and not to export or re-export the Services to prohibited
                countries or persons.
              </p>

              <h3>15.8 Government Users</h3>
              <p>
                If you are a U.S. government entity, the Services are "commercial computer software"
                and "commercial computer software documentation" with "restricted rights" as defined
                in applicable federal regulations.
              </p>

              <h3>15.9 Third-Party Beneficiaries</h3>
              <p>
                These Terms do not create any third-party beneficiary rights except as expressly stated.
              </p>

              <h3>15.10 Interpretation</h3>
              <p>
                Section headings are for convenience only and do not affect interpretation. "Including"
                means "including but not limited to." The Terms will not be construed against the
                drafting party.
              </p>
            </section>

            <section className="legal-section">
              <h2>16. Contact Information</h2>

              <p>
                For questions about these Terms of Service, please contact:
              </p>

              <div className="legal-contact">
                <p>
                  <strong>Hive Omics Legal Department</strong><br />
                  Email: <a href="mailto:legal@hiveomics.com">legal@hiveomics.com</a><br />
                  Phone: +1 (555) 123-4567<br />
                </p>
                <p>
                  <strong>For HIPAA/BAA Inquiries:</strong><br />
                  Email: <a href="mailto:legal@hiveomics.com">legal@hiveomics.com</a>
                </p>
              </div>
            </section>

            <section className="legal-section">
              <p className="legal-acknowledgment">
                <strong>ACKNOWLEDGMENT:</strong> BY USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE
                READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
              </p>
            </section>
          </div>
        </div>
      </div>
    </article>
  );
}
